server:
  port: 8765
 
spring:
  application:
    name: bigdata-zuul-gateway
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ribbon:
   ReadTimeout: 190000
   ConnectionTimeout: 190000
   eureka:
      enabled: true
 
zuul:   
  sensitive-headers: Cookie,Set-Cookie
  #Service will be mapped under the /api URI
  #prefix: /api
  # The ignoredServices disable accessing services using service name
  # with these they should be only accessed through the path we defined below.
  ignoredServices: '*'
  routes:
    security-jwt-service_users:
      path: /api/users/**
      serviceId: security-jwt-service
      stripPrefix: false
    security-jwt-service_welcome:
      path: /welcome
      serviceId: security-jwt-service
      stripPrefix: false
    bigdata-import-service:
      path: /api/bigdata/**
      serviceId: bigdata-import-service
      stripPrefix: false
    sidecar-python-service:  
      path: /api/fraud-detection/**
      serviceId: sidecar-python-service
      stripPrefix: false
